// ==========================================
// DATA_AKUN.JS — Database Bersama Semua Akun
// Dipakai oleh: katalogML.html, detail_akun.html
// ==========================================
const databaseAkun = [
  // ==========================================
  // KATALOG ML (Halaman katalogML.html)
  // ==========================================
  {
    id: "ml-001",
    nama: "BENEDETA VESSEL",
    hargaAsli: "1.000.000",
    hargaDiskon: "800.000",
    diskon: "20%",
    rank: "Mythic Glory",
    skin: "500",
    hero: "124",
    ex: "-",
    kode: "ML-001",
    gambar: "stok1.jpg",
    deskripsi: "Akun ML dengan hero Benedeta skin Vessel. Server Indonesia.",
  },
  {
    id: "ml-002",
    nama: "FANNY LEGENDS",
    hargaAsli: "1.000.000",
    hargaDiskon: "800.000",
    diskon: "20%",
    rank: "Mythic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "ML-002",
    gambar: "stok1.jpg",
    deskripsi: "Akun ML dengan hero Fanny skin Valentine. Server Indonesia.",
  },
  {
    id: "ml-003",
    nama: "GUSION LEGEND",
    hargaAsli: "1.000.000",
    hargaDiskon: "800.000",
    diskon: "20%",
    rank: "Mythic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "ML-003",
    gambar: "stok1.jpg",
    deskripsi: "Akun ML dengan hero Gusion skin Legend. Server Indonesia.",
  },
  {
    id: "ml-004",
    nama: "CHOU IORI YAGAMI",
    hargaAsli: "1.000.000",
    hargaDiskon: "800.000",
    diskon: "20%",
    rank: "Mythic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "ML-004",
    gambar: "stok1.jpg",
    deskripsi: "Akun ML dengan hero Chou skin Iori Yagami. Server Indonesia.",
  },
  {
    id: "ml-005",
    nama: "LING M-WORLD",
    hargaAsli: "1.000.000",
    hargaDiskon: "800.000",
    diskon: "20%",
    rank: "Mythic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "ML-005",
    gambar: "stok1.jpg",
    deskripsi: "Akun ML dengan hero Ling skin M-World. Server Indonesia.",
  },
  {
    id: "ml-006",
    nama: "ALUCARD LIGHTBORN",
    hargaAsli: "1.100.000",
    hargaDiskon: "330.000",
    diskon: "70%",
    rank: "Mythic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "ML-006",
    gambar: "stok1.jpg",
    deskripsi: "Akun ML dengan hero Alucard skin Lightborn. Server Indonesia.",
  },
  {
    id: "ml-007",
    nama: "ROGER PRIME M3",
    hargaAsli: "3.800.000",
    hargaDiskon: "1.140.000",
    diskon: "70%",
    rank: "Mythic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "ML-007",
    gambar: "stok1.jpg",
    deskripsi: "Akun ML dengan hero Roger skin Prime M3. Server Indonesia.",
  },
  {
    id: "ml-008",
    nama: "GRANGER LEGEND",
    hargaAsli: "4.000.000",
    hargaDiskon: "1.200.000",
    diskon: "70%",
    rank: "Mythic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "ML-008",
    gambar: "stok1.jpg",
    deskripsi: "Akun ML dengan hero Granger skin Legend. Server Indonesia.",
  },
  {
    id: "ml-009",
    nama: "LAYLA BLAZING",
    hargaAsli: "1.500.000",
    hargaDiskon: "500.000",
    diskon: "60%",
    rank: "Mythic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "ML-009",
    gambar: "akun-ml-1.jpg",
    deskripsi: "Akun ML dengan hero Layla skin Blazing. Server Indonesia.",
  },
  {
    id: "ml-010",
    nama: "ZILONG EPIC",
    hargaAsli: "900.000",
    hargaDiskon: "300.000",
    diskon: "66%",
    rank: "Mythic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "ML-010",
    gambar: "akun-ml-2.jpg",
    deskripsi: "Akun ML dengan hero Zilong skin Epic. Server Indonesia.",
  },

  // ==========================================
  // FEATURED FF (Beranda index.html — Tab FF)
  // ==========================================
  {
    id: "idx-ff-001",
    nama: "BUNDLE ALOK 1",
    hargaAsli: "",
    hargaDiskon: "504.000",
    diskon: "PROMO",
    rank: "Heroic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "FF-ALOK01",
    gambar: "logoff.jpg",
    deskripsi:
      "Akun Free Fire Bundle Alok edisi spesial. Sudah include karakter Alok.",
  },
  {
    id: "idx-ff-002",
    nama: "BUNDLE ALOK 2",
    hargaAsli: "",
    hargaDiskon: "300.000",
    diskon: "PROMO",
    rank: "Heroic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "FF-ALOK02",
    gambar: "logoff.jpg",
    deskripsi:
      "Akun Free Fire Bundle Alok edisi spesial. Sudah include karakter Alok.",
  },
  {
    id: "idx-ff-003",
    nama: "BUNDLE ALOK 3",
    hargaAsli: "",
    hargaDiskon: "450.000",
    diskon: "PROMO",
    rank: "Heroic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "FF-ALOK03",
    gambar: "logoff.jpg",
    deskripsi:
      "Akun Free Fire Bundle Alok edisi spesial. Sudah include karakter Alok.",
  },
  {
    id: "idx-ff-004",
    nama: "BUNDLE ALOK 4",
    hargaAsli: "",
    hargaDiskon: "200.000",
    diskon: "PROMO",
    rank: "Heroic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "FF-ALOK04",
    gambar: "logoff.jpg",
    deskripsi:
      "Akun Free Fire Bundle Alok edisi spesial. Sudah include karakter Alok.",
  },
  {
    id: "idx-ff-005",
    nama: "BUNDLE ALOK 5",
    hargaAsli: "",
    hargaDiskon: "650.000",
    diskon: "PROMO",
    rank: "Heroic",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "FF-ALOK05",
    gambar: "logoff.jpg",
    deskripsi:
      "Akun Free Fire Bundle Alok edisi spesial. Sudah include karakter Alok.",
  },

  // ==========================================
  // FEATURED EFOOTBALL (Beranda — Tab eFootball)
  // ==========================================
  {
    id: "idx-ef-001",
    nama: "MESSI ICONIC",
    hargaAsli: "",
    hargaDiskon: "199.000",
    diskon: "PROMO",
    rank: "Top Player",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "EF-MESSI01",
    gambar: "logoefb.jpg",
    deskripsi: "Akun eFootball dengan Messi Iconic Moment. Siap pakai.",
  },
  {
    id: "idx-ef-002",
    nama: "RONALDO",
    hargaAsli: "",
    hargaDiskon: "250.000",
    diskon: "PROMO",
    rank: "Top Player",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "EF-CR701",
    gambar: "logoefb.jpg",
    deskripsi: "Akun eFootball dengan Cristiano Ronaldo. Siap pakai.",
  },
  {
    id: "idx-ef-003",
    nama: "NEYMAR",
    hargaAsli: "",
    hargaDiskon: "350.000",
    diskon: "PROMO",
    rank: "Top Player",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "EF-NEY01",
    gambar: "logoefb.jpg",
    deskripsi: "Akun eFootball dengan Neymar Jr. Siap pakai.",
  },
  {
    id: "idx-ef-004",
    nama: "MBAPPE",
    hargaAsli: "",
    hargaDiskon: "450.000",
    diskon: "PROMO",
    rank: "Top Player",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "EF-MBP01",
    gambar: "logoefb.jpg",
    deskripsi: "Akun eFootball dengan Kylian Mbappe. Siap pakai.",
  },
  {
    id: "idx-ef-005",
    nama: "HAALAND",
    hargaAsli: "",
    hargaDiskon: "550.000",
    diskon: "PROMO",
    rank: "Top Player",
    skin: "-",
    hero: "-",
    ex: "-",
    kode: "EF-HAL01",
    gambar: "logoefb.jpg",
    deskripsi: "Akun eFootball dengan Erling Haaland. Siap pakai.",
  },
];
